PROTEINS = ['beef', 'steak', 'pork', 'chicken', 'goat', 'ham', 'lamb', 'turkey', 'rabbit', 'venison',
            'elk', 'duck', 'goose', 'buffalo', 'veal']
VEGETARIAN = ['tofu', 'seitan', 'eggplant']
FRUITS = ['apple', 'apricot', 'banana', 'blueberry', 'cherry', 'date', 'elderberry', 'fig', 'grape',
          'grapefruit', 'guava', 'plum', 'kiwi', 'kumquat', 'lemon', 'lime', 'lychee', 'mandarin',
          'mango', 'nectarine', 'orange', 'papaya', 'passion fruit', 'peach', 'pear', 'persimmon',
          'pineapple', 'plantain', 'plum', 'pomegranate', 'prune', 'pummelo', 'raspberry', 'strawberry',
          'tangerine', 'watermelon']

["Feta",
 "Egg Noodles",
 "dried tomatoes",
 "Quinoa",
 "Pasta",
 "Pine nuts",
 "Oats",
 "Whole Grain Bread",
 "Couscous",
 "Tofu",
 "Buckwheat",
 "Eggs",
 "Cottage Cheese",
 "Bulgur",
 "Popcorn",
 "Ricotta",
 "Edamame",
 "Millet",
 "Greek Yogurt",
 "Soybeans",
 "Parmesan",
 "Hemp Seed",
 "Pumpkin Seed",
 "Gruyere",
 "Swiss",
 "Peanuts",
 "Seitan",
 "Eggplant",
 "Lentils",
 "Kidney Beans",
 "Mozzarella",
 "Green Peas",
 "Cheddar",
 "Navy Beans",
 "Peanut Butter",
 "Black Beans",
 "Lima Beans",
 "Almonds",
 "Sunflower Seeds",
 "Chickpeas",
 "Tempeh",
 "Pistachios",
 "Camembert",
 "Flaxseed",
 "Cashews",
 "Tahini",
 "Chia Seeds",
 "Quorn",
 "walnuts",
 "wild rice"]

["Black beans",
"Broad beans",
"Brown beans",
"Chickpeas",
"Edamame",
"Lentils",
"Lima beans",
"Lupine",
"Kidney beans",
"Marrowfat peas",
"Soy beans",
"White beans",
"Amaranth",
"Barley",
"Bread",
"Buckwheat",
"Bulgur",
"Couscous",
"Millet",
"Oats",
"Pasta",
"Quinoa",
"Rice",
"Rijst",
"Rye bread",
"Spelt",
"Artichoke",
"Aubergine",
"Avocado",
"Beansprouts",
"Beetroot",
"Bell pepper",
"Bok choy",
"Broccoli",
"Brussels sprouts",
"Butternut squash",
"Cauliflower",
"Carrots",
"Celeriac",
"Chicory",
"Chinese cabbabe",
"Courgette",
"Cucumber",
"Endive",
"Fennel",
"Glasswort",
"Green bean",
"Haricot",
"Kale",
"Leek",
"Lettuce",
"Mushrooms",
"Onion",
"Oxheart",
"Parsnip",
"Potato",
"Pumpkin",
"Red cabbage",
"Sugar snaps",
"Spinach",
"Sweet potato",
"Tomato",
"Brazil nuts",
"Cashews",
"Hazelnuts",
"Macadamia nuts",
"Peanuts",
"Pecans",
"Pistachios",
"Walnuts",
"Chia seedS",
"Flaxseed",
"Hemp seed",
"Pumpkin seedS",
"Sesame seeds",
"Sunflower seeds",
"Seitan",
"Tempeh",
"Tofu",
"Veggieburger",
"Vegan minced meaT"]
